name: Build Unity Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Android Player

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Unity Builder
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2021.3.33f1
          targetPlatform: Android

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2021.3.33f1
          targetPlatform: Android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PrincipalPanic-APK
          path: build/Android/*.apk
